### ISSUE TITLE
can I increase `sett.nworker`?

### ISSUE THREAD

**Issue by sindhura234** [WCHN/CTseg#25]
`zoom=1/16: 12 x 16 x 17`
`sett.nworker = 0`

When executing the program it shows `sett.nworker = 0`. Is there any way that I can set number of workers ? or is that default? 
I have compile `SPM' with OpenMP support also

**Comment by brudfors** [comment]
Hello @sindhura234 

That setting does not need changing for CTseg, but only applies when multiple subject images are being registered to the atlas simultaneously (CTseg is a single-subject registration). The reasons that you see it is because CTseg back-end is [the multi-brain toolbox](https://github.com/WTCN-computational-anatomy-group/mb), which can by used to also register multiple subjects. A larger number of workers will then speed up the registration.
